const TIME_INPUT_DROPDOWN_OPTIONS_FIRST_HOUR_INTERVAL = 15;
const TIME_INPUT_DROPDOWN_OPTIONS_DEFAULT_INTERVAL = 30;

export {
  TIME_INPUT_DROPDOWN_OPTIONS_FIRST_HOUR_INTERVAL,
  TIME_INPUT_DROPDOWN_OPTIONS_DEFAULT_INTERVAL
};
