const IS_LAST_CHARACTER_DECIMAL_POINT_REGEX = /\.$/;
const MATCH_ZEROS_AFTER_DECIMAL_REGEX = /\.0+$/;
const NUMBER_WITH_THOUTHOUSANDTH_AND_DECIMAL_POINT_REGEX = /^-?([0-9]*,*)*\.?[0-9]*$/g;

export {
  IS_LAST_CHARACTER_DECIMAL_POINT_REGEX,
  MATCH_ZEROS_AFTER_DECIMAL_REGEX,
  NUMBER_WITH_THOUTHOUSANDTH_AND_DECIMAL_POINT_REGEX
};
