const DEFAULT_THOUSANDTHS_SEPARATOR = ",";
const DEFAULT_DECIMAL_NUMBER_SEPARATOR = ".";
const DEFAULT_MINUS_SIGN = "-";
const DEFAULT_NUMERALS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

export {
  DEFAULT_THOUSANDTHS_SEPARATOR,
  DEFAULT_DECIMAL_NUMBER_SEPARATOR,
  DEFAULT_MINUS_SIGN,
  DEFAULT_NUMERALS
};
