const IS_LAST_CHARACTER_DECIMAL_POINT_REGEX = /\.$/;
const MATCH_ZEROS_AFTER_DECIMAL_REGEX = /\.0+$/;
const NOT_NUMBER_OR_DECIMAL_POINT_REGEX = /[^0-9.]/g;

export {
  IS_LAST_CHARACTER_DECIMAL_POINT_REGEX,
  MATCH_ZEROS_AFTER_DECIMAL_REGEX,
  NOT_NUMBER_OR_DECIMAL_POINT_REGEX
};
